CREATE SCHEMA IF NOT EXISTS Biblioteca;

USE Biblioteca;


CREATE TABLE LIBRI(
	ISBN_ID INTEGER NOT NULL,
    TITOLO VARCHAR(150),
	ISBN VARCHAR(20) NOT NULL,
    LINGUA VARCHAR(30),
	ANNO_PUB INTEGER,
    NUM_COPIE INTEGER NOT NULL,
	
	PRIMARY KEY(ISBN_ID)
);


CREATE TABLE AUTORI(
	AUTORI_ID INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    DATA_NASCITA VARCHAR(10),
    LDN VARCHAR(20),
    
    PRIMARY KEY(AUTORI_ID)
);


CREATE TABLE STUDENTE(
	MATRICOLA INTEGER NOT NULL,
	NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
	INDIRIZZO VARCHAR(50),
    TELEFONO VARCHAR(15),
     
    PRIMARY KEY(MATRICOLA)
);


CREATE TABLE BIBLIOTECA(
	ID_BIBLIOTECA INTEGER NOT NULL,
    NOME_BIBLIOTECA VARCHAR(100),
    VIA VARCHAR(50),
    NUMERO_CIVICO VARCHAR(4),
    CAP INTEGER,
    CITTA VARCHAR(50),

    PRIMARY KEY(ID_BIBLIOTECA)
    -- FOREIGN KEY(CODICE_UNIVOCO) REFERENCES LIBRI(CODICE_UNIVOCO)
);


CREATE TABLE COPIA(
	CODICE_UNIVOCO INTEGER NOT NULL AUTO_INCREMENT,
    ISBN_ID INTEGER NOT NULL,
    NUM_COPIE INTEGER NOT NULL,
    ID_BIBLIOTECA INTEGER,
    
    PRIMARY KEY(CODICE_UNIVOCO,ISBN_ID),
    FOREIGN KEY(ID_BIBLIOTECA) REFERENCES BIBLIOTECA(ID_BIBLIOTECA),
    FOREIGN KEY(ISBN_ID) REFERENCES LIBRI(ISBN_ID)
);


CREATE TABLE SCRITTO_DA(
	ISBN_ID INTEGER NOT NULL,
    AUTORI_ID INTEGER NOT NULL,
    
    PRIMARY KEY(ISBN_ID,AUTORI_ID),
    FOREIGN KEY(ISBN_ID) REFERENCES LIBRI(ISBN_ID),
    FOREIGN KEY(AUTORI_ID) REFERENCES AUTORI(AUTORI_ID)
    
);


CREATE TABLE NOLLEGGIA(
	MATRICOLA INTEGER NOT NULL,
    CODICE_UNIVOCO INTEGER NOT NULL,
    ISBN_ID INTEGER NOT NULL, -- newlly added
    ID_BIBLIOTECA INTEGER,
    DATA_USCITA VARCHAR(10),
    DATA_RITORNO VARCHAR(10),
    
    PRIMARY KEY(MATRICOLA,CODICE_UNIVOCO),
    FOREIGN KEY(MATRICOLA) REFERENCES STUDENTE(MATRICOLA),
    FOREIGN KEY(ISBN_ID) REFERENCES COPIA(ISBN_ID),
    FOREIGN KEY(ID_BIBLIOTECA) REFERENCES COPIA(ID_BIBLIOTECA),
    FOREIGN KEY(CODICE_UNIVOCO) REFERENCES COPIA(CODICE_UNIVOCO)
    
);
-- done